
CREATE TABLE PRODUCTS
(
    ID                  BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME        VARCHAR     NOT NULL,
    BRAND               VARCHAR     NOT NULL,
    EXPIRATION_DATE     TIMESTAMP   NOT NULL,
    PRICE               NUMERIC(20,2) NOT NULL
);
